# Generated by Django 5.2.5 on 2025-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('data', models.JSONField()),
                ('survey_question_id', models.BigIntegerField()),
                ('survey_user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'encuesta_respuestas',
            },
        ),
    ]
