# Generated by Django 5.2.5 on 2025-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_encuestarespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_user_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('usuario_login', models.CharField(max_length=150)),
                ('usuario_nombre', models.CharField(max_length=255)),
                ('total_preguntas', models.IntegerField()),
                ('primera_respuesta', models.DateTimeField()),
                ('ultima_respuesta', models.DateTimeField()),
            ],
            options={
                'db_table': 'encuestas_realizadas',
                'managed': False,
            },
        ),
    ]
