# Generated by Django 5.2.5 on 2025-09-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_encuestarealizada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncuestaRealizada',
        ),
    ]
